// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSHMsgUFIOpU4Kum9cIZ79Cz_4HKhgqnM',
    appId: '1:77686619005:web:8bf99580481e7688eaaa14',
    messagingSenderId: '77686619005',
    projectId: 'pokyh-a92a5',
    authDomain: 'pokyh-a92a5.firebaseapp.com',
    storageBucket: 'pokyh-a92a5.firebasestorage.app',
    measurementId: 'G-BVG1VLJXRB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_QZTEyvc_Hh4fCiCyDnFO3F9XGVmeF3M',
    appId: '1:77686619005:android:a3eab080ee929ff5eaaa14',
    messagingSenderId: '77686619005',
    projectId: 'pokyh-a92a5',
    storageBucket: 'pokyh-a92a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBcP7z8OMZLgzsA44f-QJfToLU3d-Qois',
    appId: '1:77686619005:ios:77e33d73cdd0f73aeaaa14',
    messagingSenderId: '77686619005',
    projectId: 'pokyh-a92a5',
    storageBucket: 'pokyh-a92a5.firebasestorage.app',
    iosBundleId: 'dev.plattnericus.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBcP7z8OMZLgzsA44f-QJfToLU3d-Qois',
    appId: '1:77686619005:ios:77e33d73cdd0f73aeaaa14',
    messagingSenderId: '77686619005',
    projectId: 'pokyh-a92a5',
    storageBucket: 'pokyh-a92a5.firebasestorage.app',
    iosBundleId: 'dev.plattnericus.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSHMsgUFIOpU4Kum9cIZ79Cz_4HKhgqnM',
    appId: '1:77686619005:web:081aa78e79e1e098eaaa14',
    messagingSenderId: '77686619005',
    projectId: 'pokyh-a92a5',
    authDomain: 'pokyh-a92a5.firebaseapp.com',
    storageBucket: 'pokyh-a92a5.firebasestorage.app',
    measurementId: 'G-0JVDLHVGZN',
  );
}
